# Generated by Django 5.1.4 on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'Genel'), ('tech', 'Teknoloji'), ('gaming', 'Oyun'), ('finance', 'Finans'), ('health', 'Sağlık'), ('lifestyle', 'Yaşam')], default='general', max_length=20),
        ),
    ]
