# Generated by Django 5.1.4 on 2025-12-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0007_feedback_moderator_reply_feedback_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='twochoice_app.feedback'),
        ),
    ]
