# Generated by Django 5.1.4 on 2025-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0008_notification_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_welcome_popup',
            field=models.BooleanField(default=False),
        ),
    ]
