# Generated by Django 5.1.4 on 2025-12-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0009_userprofile_has_seen_welcome_popup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_post', 'Gönderi Onayla'), ('reject_post', 'Gönderi Reddet'), ('reply_feedback', 'Geri Bildirim Yanıtla'), ('resolve_feedback', 'Geri Bildirim Çözüldü'), ('handle_report', 'Rapor İşlemi'), ('ban_user', 'Kullanıcı Ban'), ('unban_user', 'Kullanıcı Unban'), ('unban_all', 'Tüm Yasakları Kaldır'), ('deactivate_user', 'Kullanıcı Pasif'), ('reactivate_user', 'Kullanıcı Aktif')], max_length=30)),
                ('target_type', models.CharField(choices=[('post', 'Gönderi'), ('feedback', 'Geri Bildirim'), ('report', 'Rapor'), ('user', 'Kullanıcı')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderasyon Logu',
                'verbose_name_plural': 'Moderasyon Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
