# Generated by Django 5.1.4 on 2025-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0011_feedbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_moderation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_votes',
            field=models.BooleanField(default=True),
        ),
    ]
