# Generated by Django 5.1.4 on 2025-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0012_userprofile_notify_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll_close_mode',
            field=models.CharField(choices=[('none', 'Kapanış yok'), ('24h', '24 saat sonra'), ('3d', '3 gün sonra'), ('manual', 'Manuel (tarih seç)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='poll_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
