# Generated by Django 5.1.4 on 2025-12-18 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0013_post_poll_close_mode_post_poll_closes_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='twochoice_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karar',
                'verbose_name_plural': 'Kararlar',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
