# Generated by Django 5.1.4 on 2025-12-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0014_polldecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollDecision',
        ),
    ]
