# Generated by Django 5.1.4 on 2025-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0015_delete_polldecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Taslak'), ('p', 'Yayınlandı'), ('r', 'Reddedildi')], db_index=True, default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'Genel'), ('tech', 'Teknoloji'), ('gaming', 'Oyun'), ('finance', 'Finans'), ('health', 'Sağlık'), ('lifestyle', 'Yaşam')], db_index=True, default='general', max_length=20),
        ),
    ]
