# Generated by Django 5.1.4 on 2025-12-23 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0017_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('entertainment', '🎉 Eğlence'), ('knowledge', '🧠 Bilgi & Merak'), ('education', '🎓 Okul & Eğitim'), ('daily_life', '🏡 Günlük Hayat'), ('creative', '🎨 Yaratıcı'), ('society', '🌱 Toplum & Çevre')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
