# Generated by Django 5.1.4 on 2025-12-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0019_userprofile_banner_image_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
