# Generated by Django 5.1.4 on 2025-12-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twochoice_app', '0021_add_comment_parent_and_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
